config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'flights#index'
  get '/planets', to: 'planets#index'
  get 'planets/new'
  get '/bookings/new', to: 'bookings#new'

  resources :planets
  resources :flights
  resources :bookings

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    has_many :passengers
    belongs_to :flight

    accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :origin, :class_name => "Planet"
    belongs_to :destination, :class_name => "Planet"
    has_many :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    belongs_to :booking
end

app/models/planet.rb
class Planet < ApplicationRecord
    has_many :arrivals, :foreign_key => "destination_id", :class_name =>"Flight"
    has_many :departures, :foreign_key => "origin_id", :class_name => "Flight"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def new
        @booking = Booking.new
        @flight = Flight.find(params[:flight_id].to_i)
        @seats = params[:seats].to_i
        @seats.times { @booking.passengers.build }
    end

    def create
        @booking = Booking.new(booking_params)
        if @booking.save
           @booking.passengers.each do |p|
            PassengerMailer.thank_you(p).deliver_now
            end
        redirect_to @booking
        else
        @seats = params[:seats].present? ? /(\d)/.match(params[:seats]).captures.first.to_i : 1
        @flight = Flight.find(booking_params[:flight_id].to_i)
        render 'new'
        end
    end

    def show
        @booking = Booking.find(params[:id])
        @flight = @booking.flight
    end


    private

    def booking_params
        params.require(:booking).permit(:flight_id, :passengers_attributes => [:name, :email, :booking_id])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
    def index
        @flights = Flight.all
        @flight = Flight.new
        @planet_options = Planet.all.map{ |p| [p.name, p.id] }
        @options = Planet.all.map {|p| p.name}
        @depart = params[:flight][:origin_id] unless params[:flight].nil?
        @arrival = params[:flight][:destination_id] unless params[:flight].nil?
    end

    private

    def params_flight
        params.require(:flight).permit(:origin_id, :destination_id)
    end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

    def index
        @planets = Planet.all
    end

    def new 
        @planet = Planet.new
    end

    def create
        @planet = Planet.create(params_planet)
        redirect_to planets_path
    end

private

    def params_planet
        params.require(:planet).permit(:name)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/bookings/new.html.erb
<h1> Booking </h1>

Flight n°<%= @flight.id %> -
Depart from : <%= @flight.origin.name %> - 
Going to : <%= @flight.destination.name %> - 
Duration of flight : <%= @flight.duration %> - 
Nb of passengers : <%= @seats %>

<h2> Passengers info </h2>

<%= form_for @booking do |f| %>
  <%= f.hidden_field :flight_id, value: @flight.id %> 
  <%= hidden_field_tag :flight_id, value: @flight.id %>
  <%= hidden_field_tag :seats, value: @seats %>
  <% nb = 0 %>
  <%= f.fields_for :passengers do |p| %>
    <li>
    <%= "Passenger #{nb +=1}" %>
    <br>
    <%= p.label :name %>
    <%= p.text_field :name %>
    <%= p.label :email %>
    <%= p.email_field :email %>
    </li>
  <%end%>
<%= f.submit "Submit" %>
<%end%>

app/views/bookings/show.html.erb
<% @booking.passengers.each do |p| %>
  N°de vol : <%= @flight.id %> - 
  Nom : <%= p.name %> -
  Mail : <%= p.email %> 
<%end%>

app/views/flights/_flight.html.erb
<li>
Flight n° <%= flight.id %> -
Origin: <%= flight.origin.name %> -
Destination: <%= flight.destination.name%> -
Duration : <%= flight.duration %>
</li>

app/views/flights/_search_display.html.erb
<%= form_tag new_booking_path, enforce_utf8: false , method: :get do %>
<%= hidden_field_tag :seats, params[:seats] %>
 <% flight = Flight.all.where(origin_id: @depart, destination_id: @arrival)%>
  <% flight.each do |f| %>
    <li>
    Flight n° <%= f.id %> -
    Origin: <%= f.origin.name %> -
    Destination: <%= f.destination.name%> -
    Duration : <%= f.duration %>
    <%= radio_button_tag :flight_id, f.id, false, class: ["radio", "booking-radio"] %>
    <%end%>
    </li>
<%= submit_tag "Book", name: nil, id: "booking-button", class: ["btn", "btn-primary", "btn-block"] %>
<%end%>

app/views/flights/_search_display1.html.erb
<% @flights.each do |f| %>
    <li>
    Flight n° <%= f.origin %> -
    Origin: <%= f.origin.name %> -
    Destination: <%= f.destination.name%> -
    Duration : <%= f.duration %>
<% end %>

app/views/flights/_search_form.html.erb
<%= form_for(@flight, :url => root_path, :html => { :method => 'GET'}) do |f| %>
    Origin
    <%= f.select(:origin_id, @planet_options)%>
    Destination
    <%= f.select(:destination_id, @planet_options)%>
    Nb of passengers
    <%= select_tag :seats, options_for_select([1,2,3,4]) %>
    <%= f.submit value="search" %>
<%end%>

app/views/flights/_search_form1.html.erb
<%= form_tag(root_url, enforce_utf8: false , method: :get) do %>
    <%= label_tag :origin %>
    <%= select_tag :origin, options_for_select(@options)%>
    Nb of passengers
    <%= select_tag "people", options_for_select([1,2,3,4]) %>
    <%= submit_tag value="search" %>
<%end%>

app/views/flights/index.html.erb
<h1> Search flight </h1>
<%= render 'search_form' %>
<%= render 'search_display' %>
<h2> Available flights </h2>
<%= render @flights %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/planets/_basic_form.html.erb
<%= form_for @planet do |p| %>
  <%= p.label :name %>
  <%= p.text_field :name, class: 'form-control'  %>
  <%= p.submit %>
<% end %>

app/views/planets/_planet.html.erb
<li>
    <%= planet.name %>
</li>

app/views/planets/index.html.erb
<h1> All Planets </h1>
<%= render @planets %>
<p> 
<%= link_to "new", new_planet_url %>
</p> 

app/views/planets/new.html.erb
<%= render 'basic_form' %>

app/views/shared/_methods.html.erb
<div>
# Select method
<select name = "planet_id">
  <% @planets.each do |planet| %>
    <option value = "<%=planet.id%>"> <%= planet.name%></option>
  <% end %>
</select>
</div>

<div>
# Select_tag method 1
<%= select_tag(:origin_id, options_for_select(@planet_options)) %>
<%= select_tag(:destination_id, options_for_select(@planet_options)) %>
</div>

<div>
# Select_tag method 2
<%= select(:flight, :origin_id, @planet_options)%>
<%= select(:flight, :destination_id, @planet_options)%>
</div>

<div>
# Select_tag method 2 with nested form_for
<%= form_for @flight do |f| %>
    <%= f.select(:origin_id, @planet_options)%>
    <%= f.select(:destination_id, @planet_options)%>
    <%= f.select(:duration, @duration_options)%>
    <%= f.submit %>
<%end%>
</div>

<div>
# Select_tag method 3 to overcome empty params pb
<%= form_tag(root_url, enforce_utf8: false , method: :get) do %>
  <%= label_tag :origin %>
  <%= select_tag :origin_id, grouped_options_for_select(@planet_options, params[:origin_id])%>
  <%= label_tag :destination %>
  <%= select_tag :destination_id, grouped_options_for_select(@planet_options, params[:destination_id])%>
  <%= label_tag :seats %>
  <%= select_tag :seats, options_for_select([["Single", 1], ["2 seats", 2], ["3 seats", 3], ["4 seats", 4]], params[:seats]), { include_blank: "Select", class: "form-control" } %>
  <%= submit_tag "Search", name: nil%>
  <% end %>
</div>